config/routes.rb
MobileUserTestApp::Application.routes.draw do
  root to: 'static_pages#home'
  mount Split::Dashboard, :at => 'split'
  
  match 'social_dialog' => 'static_pages#social_dialog'
  match 'switch_to_mobile_format' => 'static_pages#switch_to_mobile_format'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Mobylette::RespondToMobileRequests
  protect_from_forgery
 
  before_filter :set_request_format
  
  
  def set_request_format
    if is_mobile_request? && request.format.to_s == "text/html"
      request.format = :mobile
    elsif is_mobile_request? && request.format.to_s == "text/javascript"
      request.format = :mobilejs
    end
  end

  mobylette_config do |config|
    config[:skip_xhr_requests] = false
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home        
    respond_to do |format|
      format.mobile
      format.html
    end
  end
  
  def social_dialog    
    render action: 'social_dialog', formats: [:mobile] 
  end
  
  def switch_to_mobile_format
    session[:mobylette_override] = :force_mobile
    redirect_to action: 'home', formats: [:mobile] 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobileUserTestApp</title>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.mobile" %>  

  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div data-role="page" id="demo-page" data-theme="d" data-url="demo-page">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobile Version!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.mobile" %>  
  <%= stylesheet_link_tag    "jquery.mobile.min.css" %>  
  <%= csrf_meta_tags %>
</head>
<body>
<div data-role="page" id="demo-page" data-theme="d" data-url="demo-page">
  <%= yield %>
</div>


</body>
</html>

app/views/shared/_footer.mobile.erb
<div data-role="footer" data-position="fixed">
    <div data-role="navbar">
        <ul>
            <li class="ui-body-a"><a href="#" data-icon="home" data-iconpos="top" data-shadow="false" data-iconshadow="false" class="ui-icon-nodisc"></a></li>
            <li class="ui-body-a"><a href="#" data-icon="gear" data-iconpos="top" data-shadow="false" data-iconshadow="false" class="ui-icon-nodisc"></a></li>
            <li class="ui-body-a"><a href="<%= social_dialog_path %>" data-icon="plus" data-rel="dialog" data-iconpos="top" data-shadow="false" data-iconshadow="false" class="ui-icon-nodisc"></a></li>
        </ul>
    </div><!-- /navbar -->
</div><!-- /footer -->

app/views/shared/_header_no_sidepanel_icon.mobile.erb
<div data-role="header" data-theme="b">
    <h1>Mobile UX test app</h1>
</div><!-- /header -->

app/views/shared/_header_sidepanel_icon.mobile.erb
<div data-role="header" data-theme="b">
    <h1>Mobile UX test app</h1>
    <a href="#left-panel" data-theme="b" data-icon="arrow-r" data-iconpos="notext" data-shadow="false" data-iconshadow="false" class="ui-icon-nodisc">Menu</a>
</div><!-- /header -->

app/views/shared/_sidebar.mobile.erb
<div data-role="panel" id="left-panel" data-theme="b">
        <a href="#" data-rel="close" data-role="button" data-mini="false" data-inline="false" data-icon="home" data-iconpos="right">Home</a>
        <a href="#" data-rel="close" data-role="button" data-mini="false" data-inline="false" data-icon="gear" data-iconpos="right">Settings</a>
        <a href="<%= social_dialog_path %>" data-rel="dialog" data-role="button" data-mini="false" data-inline="false" data-icon="plus" data-iconpos="right">Share</a>
        <a href="#" data-rel="close" data-role="button" data-mini="false" data-inline="false" data-icon="delete" data-iconpos="right">Close</a>
</div><!-- /panel -->


<%= javascript_tag :defer => 'defer' do -%>

    $( document ).on( "pageinit", "#demo-page", function() {
        $( document ).on( "swipeleft", "#demo-page", function( e ) {
            if ( $.mobile.activePage.jqmData( "panel" ) !== "open" ) {
                if ( e.type === "swiperight" ) {
                    $( "#left-panel" ).panel( "open" );
                }
            }
        });
    });

<% end -%>

app/views/shared/_text_content.mobile.erb
<div data-role="content">
    <h1>Some awesome content</h1>
    
    <p>This content is so awesome that users will want to share it with their social contacts.</p>

    <p>But the question is: Which is the optimum way to encourage them to share?</p>
</div>

app/views/static_pages/home.html.erb
<div data-role="header" data-theme="b">
    <h1>Desktop view</h1>
</div><!-- /header -->

<div data-role="content">
    <a href="<%= switch_to_mobile_format_path %>" data-role="button" data-mini="true" data-inline="false" data-theme="b" data-iconpos="right">Switch to Mobile Format</a>
</div>


<%= javascript_tag :defer => 'defer' do -%>

    $.mobile.navigate( "/" );

<% end -%>

app/views/static_pages/home.mobile.erb
<% ab_test("social_share", "sidepanel", "footer") do |menu| %>
  <% if menu == "sidepanel" %>
    <%= render 'shared/header_sidepanel_icon' %>
    <%= render 'shared/text_content' %>
    <%= render 'shared/sidebar' %>
  <% elsif menu == "footer" %>
    <%= render 'shared/header_no_sidepanel_icon' %>  
    <%= render 'shared/text_content' %>
    <%= render 'shared/footer' %>
  <% end %>  
<% end %>

app/views/static_pages/social_dialog.mobile.erb
<div role="dialog" class="ui-dialog-contain ui-corner-all ui-overlay-shadow" id="share_dialog">
    <div data-role="header" data-theme="d"class="ui-corner-top ui-header ui-bar-d" role="banner">
        <h1 class="ui-title" role="heading" aria-level="1">Share</h1>
    </div>

    <div data-role="content" data-theme="c" class="ui-corner-bottom ui-content ui-body-c" role="main">
        <h1>Share this awesome content with your friends?</h1>
        <fieldset class="ui-grid-a">
            <div class="ui-block-a">
                <%= link_to content_tag(:span, content_tag(:span, "Facebook", class: "ui-btn-text"), class: "ui-btn-inner ui-btn-corner-all"), 
                            root_path(:format => :mobile), 
                            :class => "ui-btn ui-shadow ui-btn-corner-all ui-btn-up-b", 
                            :data => { role: "button", theme: "b", corners: "false", shadow: "true", iconshadow: "true", wrapperels: "span" }
                 %>
            </div>

            <div class="ui-block-b">
                <%= link_to content_tag(:span, content_tag(:span, "Twitter", class: "ui-btn-text"), class: "ui-btn-inner ui-btn-corner-all"), 
                            root_path(:format => :mobile), 
                            :class => "ui-btn ui-shadow ui-btn-corner-all ui-btn-up-b", 
                            :data => { role: "button", theme: "b", corners: "false", shadow: "true", iconshadow: "true", wrapperels: "span" }
                 %>
            </div>

            <div class="ui-block-a">
                <%= link_to content_tag(:span, content_tag(:span, "Google +", class: "ui-btn-text"), class: "ui-btn-inner ui-btn-corner-all"), 
                            root_path(:format => :mobile), 
                            :class => "ui-btn ui-shadow ui-btn-corner-all ui-btn-up-b", 
                            :data => { role: "button", theme: "b", corners: "false", shadow: "true", iconshadow: "true", wrapperels: "span" }
                 %>
            </div>
        </fieldset>
    </div>
</div>

<% finished("social_share") %>